name: final_practice
description: Final Practice.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  connectivity_plus: ^2.1.0
  fluttertoast: ^8.0.8
  flutter_simple_dependency_injection: ^2.0.0
  global_configuration: ^2.0.0-nullsafety.1
  dots_indicator: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.4
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0+1
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  youtube_player_iframe: ^2.2.2
  flutter_inappwebview: ^5.3.2
  photo_view: ^0.13.0
  after_layout: ^1.1.0

  flutter_bloc: ^7.3.3
  equatable: ^2.0.3
  shared_preferences: ^2.0.9

  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_database: ^9.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/config/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf

